language: python

python:
  - "3.6"
  - "3.8"

before_install:
  - cd api/
  - pip install -r requirements.txt
  - printf "from hashlib import sha256\n\ndef hash_password(password):    return sha256(password.encode('utf-8')).hexdigest()\n" > application/passwords.py

script:
  - python3 unittests.py

after_success:
  - pip install coverage codacy-coverage
  - coverage run --source application/ unittests.py
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - rm coverage.xml .coverage
