language: python

python:
  - "3.6"
  - "3.8"

script:
  - cd api/
  - pip install -r requirements.txt
  - printf "def hash_password(password):\n    return password" > application/passwords.py
  - python3 unittests.py
